// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL.trim() === "") {
  throw new Error(
    "Missing env.VITE_SUPABASE_URL. Please add it to your .env file.\n" +
      "Example: VITE_SUPABASE_URL=https://your-project.supabase.co\n" +
      `Current value: ${
        SUPABASE_URL === undefined ? "undefined" : `"${SUPABASE_URL}"`
      }`
  );
}

// Validate URL format
try {
  const url = new URL(SUPABASE_URL);
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error(
      `Invalid protocol: ${url.protocol}. Must be http:// or https://`
    );
  }
} catch (error) {
  throw new Error(
    `Invalid VITE_SUPABASE_URL format: "${SUPABASE_URL}". Must be a valid HTTP or HTTPS URL.\n` +
      "Example: VITE_SUPABASE_URL=https://your-project.supabase.co"
  );
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.trim() === "") {
  throw new Error(
    "Missing env.VITE_SUPABASE_PUBLISHABLE_KEY. Please add it to your .env file.\n" +
      "Example: VITE_SUPABASE_PUBLISHABLE_KEY=your-anon-key\n" +
      `Current value: ${
        SUPABASE_PUBLISHABLE_KEY === undefined
          ? "undefined"
          : `"${SUPABASE_PUBLISHABLE_KEY}"`
      }`
  );
}

// Validate that the key matches the project URL
try {
  const urlMatch = SUPABASE_URL.match(/https?:\/\/([^.]+)\.supabase\.co/);
  const urlProjectId = urlMatch ? urlMatch[1] : null;

  // Decode JWT to get project reference
  const keyParts = SUPABASE_PUBLISHABLE_KEY.split(".");
  if (keyParts.length === 3) {
    const payload = JSON.parse(atob(keyParts[1]));
    const keyProjectRef = payload.ref;

    if (urlProjectId && keyProjectRef && urlProjectId !== keyProjectRef) {
      throw new Error(
        `❌ PROJECT MISMATCH!\n\n` +
          `Your Supabase URL is for project: ${urlProjectId}\n` +
          `But your API key is for project: ${keyProjectRef}\n\n` +
          `To fix this:\n` +
          `1. Go to https://app.supabase.com\n` +
          `2. Open project: ${urlProjectId}\n` +
          `3. Go to Settings > API\n` +
          `4. Copy the "anon" or "public" key\n` +
          `5. Update VITE_SUPABASE_PUBLISHABLE_KEY in your .env file\n` +
          `6. Restart your dev server`
      );
    }
  }
} catch (error: any) {
  // If it's our custom error, throw it
  if (error.message.includes("PROJECT MISMATCH")) {
    throw error;
  }
  // Otherwise, just log a warning (key might not be a JWT)
  if (import.meta.env.DEV) {
    console.warn("⚠️ Could not validate key project match:", error.message);
  }
}

// Debug: Log configuration (remove in production)
if (import.meta.env.DEV) {
  console.log("🔑 Supabase URL:", SUPABASE_URL);
  console.log("🔑 Supabase Key length:", SUPABASE_PUBLISHABLE_KEY.length);

  // Check if key contains newlines
  if (
    SUPABASE_PUBLISHABLE_KEY.includes("\n") ||
    SUPABASE_PUBLISHABLE_KEY.includes("\r")
  ) {
    console.error(
      "❌ ERROR: Supabase key contains line breaks! This will cause authentication to fail."
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a singleton instance to avoid multiple client warnings
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const supabase = (() => {
  if (!supabaseInstance) {
    supabaseInstance = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      }
    );
  }
  return supabaseInstance;
})();
